services:
  mcc.testtask.app:
    image: mcc.testtask.app
    build:
      context: .
      dockerfile: MCC.TestTask.App/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - postgres
      - postgres-hangfire
      
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-hangfire:
    image: postgres:latest
    container_name: postgres_hangfire_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hangfire
    volumes:
      - postgres_hangfire_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
  postgres_hangfire_data:
    driver: local